import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sections/navs/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`home-bg ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid lg:grid-cols-12  home-bg h-screen">
          <div className="col-span-3">
            <Sidebar />
          </div>
          <div className="col-span-9">{children}</div>
        </div>
      </body>
    </html>
  );
}
